# -*- coding: utf-8 -*-
"""pingpong26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qcItDx0LIEeKRLx2qcVkc-m_zaqvN-U3
"""

import streamlit as st
import pandas as pd
import random
from itertools import combinations

# Oldal beállítása
st.set_page_config(page_title="Ping-Pong 2026", layout="wide")

# --- ADATOK INICIALIZÁLÁSA ---
if 'players' not in st.session_state:
    st.session_state.players = []
if 'matches' not in st.session_state:
    st.session_state.matches = []
if 'tournament_started' not in st.session_state:
    st.session_state.tournament_started = False

# --- FUNKCIÓK ---
def generate_matches(player_list):
    """Mindenki játszik mindenkivel (Round Robin), véletlen sorrendben."""
    all_pairings = list(combinations(player_list, 2))
    random.shuffle(all_pairings)
    matches = []
    for p1, p2 in all_pairings:
        matches.append({"A": p1, "B": p2, "score_A": 0, "score_B": 0, "played": False})
    return matches

def calculate_leaderboard():
    """Kiszámolja a ranglistát az adatok alapján."""
    stats = {p: {"Győzelem": 0, "Vereség": 0, "Szerzett pont": 0, "Kapott pont": 0} for p in st.session_state.players}

    for m in st.session_state.matches:
        if m["played"]:
            stats[m["A"]]["Szerzett pont"] += m["score_A"]
            stats[m["A"]]["Kapott pont"] += m["score_B"]
            stats[m["B"]]["Szerzett pont"] += m["score_B"]
            stats[m["B"]]["Kapott pont"] += m["score_A"]

            if m["score_A"] > m["score_B"]:
                stats[m["A"]]["Győzelem"] += 1
                stats[m["B"]]["Vereség"] += 1
            elif m["score_B"] > m["score_A"]:
                stats[m["B"]]["Győzelem"] += 1
                stats[m["A"]]["Vereség"] += 1

    df = pd.DataFrame.from_dict(stats, orient='index').reset_index()
    df.columns = ['Játékos', 'Győzelem', 'Vereség', 'Szerzett P.', 'Kapott P.']
    df['Pontkülönbség'] = df['Szerzett P.'] - df['Kapott P.']
    return df.sort_values(by=['Győzelem', 'Pontkülönbség'], ascending=False)

# --- FELHASZNÁLÓI FELÜLET ---

st.title("🏓 Profi Ping-Pong Verseny Dashboard")

# 1. SZAKASZ: Játékosok rögzítése
if not st.session_state.tournament_started:
    st.subheader("1. Nevezés")
    new_player = st.text_input("Játékos neve:", key="p_input")
    if st.button("Hozzáadás"):
        if new_player and new_player not in st.session_state.players:
            st.session_state.players.append(new_player)
            st.rerun()

    st.write(f"Regisztrált játékosok ({len(st.session_state.players)}): {', '.join(st.session_state.players)}")

    if len(st.session_state.players) > 1:
        if st.button("Sorsolás és Verseny Indítása 🚀", type="primary"):
            st.session_state.matches = generate_matches(st.session_state.players)
            st.session_state.tournament_started = True
            st.rerun()

# 2. SZAKASZ: Aktív verseny
else:
    tab1, tab2 = st.tabs(["📊 Eredmények & Ranglista", "📝 Pontok Beírása"])

    with tab1:
        st.subheader("Aktuális Állás")
        leaderboard = calculate_leaderboard()
        st.table(leaderboard) # Vagy st.dataframe(leaderboard, use_container_width=True)

        st.subheader("Meccsek állapota")
        for m in st.session_state.matches:
            status = "✅" if m["played"] else "⏳"
            st.write(f"{status} {m['A']} vs {m['B']} — Eredmény: {m['score_A']}:{m['score_B']}")

    with tab2:
        st.subheader("Meccs eredményének rögzítése")
        # Csak a még le nem játszott meccseket mutatjuk
        pending_matches = [f"{m['A']} vs {m['B']}" for m in st.session_state.matches if not m["played"]]

        if pending_matches:
            selected_match_idx = st.selectbox("Melyik meccs zárult le?", range(len(st.session_state.matches)))
            match = st.session_state.matches[selected_match_idx]

            if not match["played"]:
                col1, col2 = st.columns(2)
                with col1:
                    score_a = st.number_input(f"{match['A']} pontjai:", min_value=0, max_value=30, step=1)
                with col2:
                    score_b = st.number_input(f"{match['B']} pontjai:", min_value=0, max_value=30, step=1)

                if st.button("Eredmény Mentése"):
                    st.session_state.matches[selected_match_idx]["score_A"] = score_a
                    st.session_state.matches[selected_match_idx]["score_B"] = score_b
                    st.session_state.matches[selected_match_idx]["played"] = True
                    st.success("Mentve!")
                    st.rerun()
            else:
                st.info("Ez a meccs már lezárult. Válassz egy másikat!")
        else:
            st.balloons()
            st.success("Minden meccs lezajlott! Gratulálunk a győztesnek!")
            if st.button("Új verseny indítása"):
                st.session_state.clear()
                st.rerun()